### ISSUE TITLE
Requested accounts with undefined info don't show up in manager panel

### ISSUE THREAD

**Issue by nathunsmitty** [uclaradio/uclaradio.com#125]
## Context

I tried to approve people on panel, only to find there was no list to approve!

## Expected Behavior

A section on the right should list all users with panel accounts and if any users requested to be added.

## Current Behavior

There isn't that section on the right!

## Possible Solution

The error that shows up in console is as follows--note: I disabled minification in the build process so all *.min.js files displayed actually readable code. 

```
panelmanager.min.js:1432 Uncaught TypeError: Cannot read property 'length' of undefined
    at http://localhost:3000/build/panelmanager.min.js:1432:68
    at Array.map (native)
    at Constructor.render (http://localhost:3000/build/panelmanager.min.js:1422:38)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:3000/build/vendors.js:7598:35)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:3000/build/vendors.js:7618:33)
    at ReactCompositeComponentWrapper.wrapper [as _renderValidatedComponent] (http://localhost:3000/build/vendors.js:1371:22)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3000/build/vendors.js:7231:31)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (http://localhost:3000/build/vendors.js:1371:22)
    at Object.mountComponent (http://localhost:3000/build/vendors.js:5549:36)
    at ReactDOMComponent.mountChildren (http://localhost:3000/build/vendors.js:14093:45)
```

## Screenshot
![screen shot 2017-07-16 at 12 19 16 pm](https://user-images.githubusercontent.com/5677971/28250874-7c2a8dce-6a27-11e7-8d86-1e6e6e2dc81b.png)

## Steps to Reproduce

1. Be a Manager in panel
2. Log in
3. Go to `/panel/manager`

## Your Environment

- [x] __Desktop__:  
Operating System:  
- [x] Chrome (__Version:__ 58.0.3029.96)
- [ ] Firefox (__Version:__ )
- [x] Safari (__Version:__ 10.1.1)
- [ ] Opera (__Version:__ )
- [ ] IE (__Version:__ )
- [ ] EDGE (__Version:__ )
_Probably applies to all browsers, I just haven't tested them all._

- [ ] __Mobile__:  
Device:  
Operating System:  
- [ ] Chrome (__Version:__ )
- [ ] Firefox (__Version:__ )
- [ ] Safari (__Version:__ )
- [ ] Opera (__Version:__ )

**Comment by nathunsmitty** [comment]
**Update: ** the bug was caused by someone requesting an account and not submitting their email and full name, hence leading to `undefined` objects in the code. Let's add some checking for that!

**Comment by binerys** [comment]
Moving to https://github.com/uclaradio/panel and https://github.com/uclaradio/uclaradio-api
